server:
  port: 8086
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.bidnow.media: DEBUG
    org.apache.kafka.clients.NetworkClient: ERROR

spring:
  application:
    name: media-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: media-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        reconnect.backoff.ms: 5000
        reconnect.backoff.max.ms: 30000
    listener:
      observation-enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mail:
  from: ${MAIL_FROM}

aws:
  s3:
    ACCESS_KEY: ${AWS_ACCESS_KEY}
    SECRET_KEY: ${AWS_SECRET_KEY}
    REGION: ${AWS_REGION}
    BUCKET_NAME: ${AWS_BUCKET_NAME}
    ENDPOINT: ${AWS_ENDPOINT}

supabase:
  public-url: ${SUPABASE_PUBLIC_URL}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0  # reduce to 0.1 or lower in production
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      kafka:
        enabled: true
      show-details: always

springdoc:
  api-docs:
    path: /api/v1/media/v3/api-docs
  swagger-ui:
    enabled: false

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}