server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/admin/users/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/admin/profiles/**
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/api/v1/auctions/**
        - id: bidding-service
          uri: lb://bidding-service
          predicates:
            - Path=/api/v1/bids/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/v1/wallets/**
        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/v1/media/**, /api/v1/admin/templates/**, /api/v1/admin/email-logs/**, /api/v1/admin/audit-logs
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

        default-filters:
          - name: DeduplicateResponseHeader
            args:
              name: Access-Control-Allow-Origin Access-Control-Allow-Credentials
              strategy: RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Identity Service
        url: /api/v1/auth/v3/api-docs
      - name: User Service
        url: /api/v1/users/v3/api-docs
      - name: Auction Service
        url: /api/v1/auctions/v3/api-docs
      - name: Bidding Service
        url: /api/v1/bids/v3/api-docs
      - name: Wallet Service
        url: /api/v1/wallets/v3/api-docs
      - name: Media Service
        url: /api/v1/media/v3/api-docs
    display-request-duration: true
    groups-order: ASC
  api-docs:
    path: /v3/api-docs
