import { AuctionStatus } from './design-tokens'
import type { Auction, BidHistoryItem } from '@/types/ui/auction.ui'

export const MOCK_CURRENT_USER_ID = 'current-user'

export const MOCK_AUCTIONS: Auction[] = [
  {
    id: '1',
    title: 'Vintage Omega Seamaster 1968',
    description: 'An exceptional example of the iconic Omega Seamaster in near-mint condition. Dial, hands, and case all original. Serviced 2023. Rare cal. 565 movement, original dial, box and papers.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u1',
    startingPrice: 50_000,
    currentBid: 135_000,
    totalBids: 14,
    watchers: 42,
    startsAt: new Date(Date.now() - 3_600_000),
    endsAt:   new Date(Date.now() + 7_200_000),
    status: AuctionStatus.Active,
    isFeatured: true,
    condition: 'Near Mint',
    reserveMet: true,
    seller: { id: 'u1', name: 'Marcus W.', rating: 4.9, totalAuctions: 218 },
  },
  {
    id: '2',
    title: 'Gibson Les Paul Custom 1974',
    description: 'All-original Black Beauty with case, OHSC.',
    imageUrls: [],
    categoryId: 'music',
    sellerId: 'u2',
    startingPrice: 100_000,
    currentBid: 280_000,
    totalBids: 31,
    watchers: 89,
    startsAt: new Date(Date.now() - 7_200_000),
    endsAt:   new Date(Date.now() + 3_600_000),
    status: AuctionStatus.EndingSoon,
    isFeatured: true,
    condition: 'Good',
    reserveMet: true,
    seller: { id: 'u2', name: 'Vintage Strings', rating: 4.7, totalAuctions: 132 },
  },
  {
    id: '3',
    title: 'First Edition Harry Potter Philosopher\'s Stone',
    description: 'Bloomsbury 1997, first print run, unread condition.',
    imageUrls: [],
    categoryId: 'books',
    sellerId: 'u3',
    startingPrice: 200_000,
    currentBid: 540_000,
    totalBids: 57,
    watchers: 203,
    startsAt: new Date(Date.now() - 86_400_000),
    endsAt:   new Date(Date.now() + 1_800_000),
    status: AuctionStatus.Critical,
    isFeatured: true,
    condition: 'Excellent',
    reserveMet: true,
    seller: { id: 'u3', name: 'Rare Books Co.', rating: 4.8, totalAuctions: 76 },
  },
  {
    id: '4',
    title: 'Patek Philippe Nautilus 5711',
    description: 'Ref. 5711/1A-014, olive dial, full set.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u4',
    startingPrice: 1_000_000,
    currentBid: 1_850_000,
    totalBids: 9,
    watchers: 117,
    startsAt: new Date(Date.now() - 3_600_000),
    endsAt:   new Date(Date.now() + 14_400_000),
    status: AuctionStatus.Active,
    isFeatured: false,
    condition: 'Mint',
    reserveMet: false,
    seller: { id: 'u4', name: 'Atelier Forty Six', rating: 4.9, totalAuctions: 311 },
  },
  {
    id: '5',
    title: 'Nike Air Jordan 1 Retro High OG Chicago 1985',
    description: 'DS pair, original box, size 10.5.',
    imageUrls: [],
    categoryId: 'sneakers',
    sellerId: 'u5',
    startingPrice: 30_000,
    currentBid: 98_000,
    totalBids: 22,
    watchers: 134,
    startsAt: new Date(Date.now() - 10_800_000),
    endsAt:   new Date(Date.now() + 10_800_000),
    status: AuctionStatus.Active,
    isFeatured: false,
    condition: 'Deadstock',
    reserveMet: true,
    seller: { id: 'u5', name: 'Sole Archive', rating: 4.6, totalAuctions: 89 },
  },
  {
    id: '6',
    title: 'Rolex Daytona 6263 Paul Newman',
    description: 'Exotic dial, tropical registers, service papers.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u6',
    startingPrice: 800_000,
    currentBid: 1_200_000,
    totalBids: 6,
    watchers: 88,
    startsAt: new Date(Date.now() - 5_400_000),
    endsAt:   new Date(Date.now() + 18_000_000),
    status: AuctionStatus.Active,
    isFeatured: false,
    condition: 'Very Good',
    reserveMet: false,
    seller: { id: 'u6', name: 'Geneva Vault', rating: 5.0, totalAuctions: 44 },
  },
  {
    id: '7',
    title: 'Banksy "Girl with Balloon" Original',
    description: 'Signed screen print, COA, gallery framed.',
    imageUrls: [],
    categoryId: 'art',
    sellerId: 'u7',
    startingPrice: 500_000,
    currentBid: 920_000,
    totalBids: 18,
    watchers: 271,
    startsAt: new Date(Date.now() - 21_600_000),
    endsAt:   new Date(Date.now() + 21_600_000),
    status: AuctionStatus.Active,
    isFeatured: false,
    condition: 'Excellent',
    reserveMet: true,
    seller: { id: 'u7', name: 'Street Art Gallery', rating: 4.8, totalAuctions: 57 },
  },
  {
    id: '8',
    title: 'Leica M3 Double Stroke + Summicron 50mm f/2',
    description: 'Serial #700xxx, CLA 2023, pristine glass.',
    imageUrls: [],
    categoryId: 'cameras',
    sellerId: 'u8',
    startingPrice: 40_000,
    currentBid: 75_000,
    totalBids: 11,
    watchers: 56,
    startsAt: new Date(Date.now() - 14_400_000),
    endsAt:   new Date(Date.now() + 28_800_000),
    status: AuctionStatus.Active,
    isFeatured: false,
    condition: 'Near Mint',
    reserveMet: true,
    seller: { id: 'u8', name: 'Classic Glass', rating: 4.7, totalAuctions: 103 },
  },
  // --- Test states ---
  {
    id: '9',
    title: '1968 Heuer Carrera 2447NS — Black Dial',
    description: 'A handsome example of the second-execution Carrera reference 2447NS, produced for just a few years in the late 1960s. The black-on-white dial layout is the most photogenic of the line and remains highly collectible. Original Valjoux 72 movement, factory crown, unpolished stainless-steel case. Acquired from a single-owner Swiss estate; serviced 2024 by an authorised independent watchmaker. Condition: Excellent (8/10).',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u9',
    startingPrice: 850_000,
    currentBid: 850_000,
    totalBids: 0,
    watchers: 134,
    startsAt: new Date(Date.now() + 7_200_000),   // starts in 2 h
    endsAt:   new Date(Date.now() + 93_600_000),  // ends in ~26 h
    status: AuctionStatus.Scheduled,
    isFeatured: false,
    condition: 'Excellent (8/10)',
    reserveMet: false,
    seller: { id: 'u9', name: 'Atelier Forty Six', rating: 4.9, totalAuctions: 218 },
  },
  {
    id: '10',
    title: 'Vintage Rolex Submariner 5513 Maxi Dial',
    description: 'Original matte dial, all-original case, service box included.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u1',
    winnerId: MOCK_CURRENT_USER_ID,
    startingPrice: 300_000,
    currentBid: 940_000,
    totalBids: 32,
    watchers: 189,
    startsAt: new Date(Date.now() - 172_800_000),
    endsAt:   new Date(Date.now() - 3_600_000),   // ended 1 h ago
    status: AuctionStatus.Won,
    isFeatured: false,
    condition: 'Very Good',
    reserveMet: true,
    seller: { id: 'u1', name: 'Marcus W.', rating: 4.9, totalAuctions: 218 },
  },
  {
    id: '11',
    title: 'Patek Philippe Calatrava 3796 White Gold',
    description: 'Ultra-thin dress watch, original crown, papers from 1982.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u4',
    winnerId: 'mw_collector',
    startingPrice: 400_000,
    currentBid: 720_000,
    totalBids: 19,
    watchers: 94,
    startsAt: new Date(Date.now() - 259_200_000),
    endsAt:   new Date(Date.now() - 7_200_000),   // ended 2 h ago
    status: AuctionStatus.Lost,
    isFeatured: false,
    condition: 'Excellent',
    reserveMet: true,
    seller: { id: 'u4', name: 'Atelier Forty Six', rating: 4.9, totalAuctions: 311 },
  },
]

export const MOCK_BIDS: BidHistoryItem[] = [
  { id: 'b1', auctionId: '1', bidderId: 'u5', amount: 135_000, placedAt: new Date(Date.now() - 60_000),  isAutoBid: false, bidderName: 'Alex K.',    isCurrentUser: false, isWinning: true  },
  { id: 'b2', auctionId: '1', bidderId: 'u6', amount: 130_000, placedAt: new Date(Date.now() - 180_000), isAutoBid: true,  bidderName: 'Maya S.',    isCurrentUser: false, isWinning: false },
  { id: 'b3', auctionId: '1', bidderId: 'me', amount: 125_000, placedAt: new Date(Date.now() - 300_000), isAutoBid: false, bidderName: 'You',        isCurrentUser: true,  isWinning: false },
]
