import { AuctionStatus } from './design-tokens'
import type { Auction, BidHistoryItem } from '@/types/auction'

export const MOCK_AUCTIONS: Auction[] = [
  {
    id: '1',
    title: 'Vintage Omega Seamaster 1968',
    description: 'An exceptional example of the iconic Omega Seamaster in near-mint condition. Dial, hands, and case all original. Serviced 2023. Rare cal. 565 movement, original dial, box and papers.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u1',
    startingPrice: 50_000,
    currentBid: 135_000,
    totalBids: 14,
    watchers: 42,
    startsAt: new Date(Date.now() - 3_600_000),
    endsAt:   new Date(Date.now() + 7_200_000),
    status: AuctionStatus.Active,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Gibson Les Paul Custom 1974',
    description: 'All-original Black Beauty with case, OHSC.',
    imageUrls: [],
    categoryId: 'music',
    sellerId: 'u2',
    startingPrice: 100_000,
    currentBid: 280_000,
    totalBids: 31,
    watchers: 89,
    startsAt: new Date(Date.now() - 7_200_000),
    endsAt:   new Date(Date.now() + 3_600_000),
    status: AuctionStatus.EndingSoon,
    isFeatured: true,
  },
  {
    id: '3',
    title: 'First Edition Harry Potter Philosopher\'s Stone',
    description: 'Bloomsbury 1997, first print run, unread condition.',
    imageUrls: [],
    categoryId: 'books',
    sellerId: 'u3',
    startingPrice: 200_000,
    currentBid: 540_000,
    totalBids: 57,
    watchers: 203,
    startsAt: new Date(Date.now() - 86_400_000),
    endsAt:   new Date(Date.now() + 1_800_000),
    status: AuctionStatus.Critical,
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Patek Philippe Nautilus 5711',
    description: 'Ref. 5711/1A-014, olive dial, full set.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u4',
    startingPrice: 1_000_000,
    currentBid: 1_850_000,
    totalBids: 9,
    watchers: 117,
    startsAt: new Date(Date.now() - 3_600_000),
    endsAt:   new Date(Date.now() + 14_400_000),
    status: AuctionStatus.Active,
    isFeatured: false,
  },
  {
    id: '5',
    title: 'Nike Air Jordan 1 Retro High OG Chicago 1985',
    description: 'DS pair, original box, size 10.5.',
    imageUrls: [],
    categoryId: 'sneakers',
    sellerId: 'u5',
    startingPrice: 30_000,
    currentBid: 98_000,
    totalBids: 22,
    watchers: 134,
    startsAt: new Date(Date.now() - 10_800_000),
    endsAt:   new Date(Date.now() + 10_800_000),
    status: AuctionStatus.Active,
    isFeatured: false,
  },
  {
    id: '6',
    title: 'Rolex Daytona 6263 Paul Newman',
    description: 'Exotic dial, tropical registers, service papers.',
    imageUrls: [],
    categoryId: 'watches',
    sellerId: 'u6',
    startingPrice: 800_000,
    currentBid: 1_200_000,
    totalBids: 6,
    watchers: 88,
    startsAt: new Date(Date.now() - 5_400_000),
    endsAt:   new Date(Date.now() + 18_000_000),
    status: AuctionStatus.Active,
    isFeatured: false,
  },
  {
    id: '7',
    title: 'Banksy "Girl with Balloon" Original',
    description: 'Signed screen print, COA, gallery framed.',
    imageUrls: [],
    categoryId: 'art',
    sellerId: 'u7',
    startingPrice: 500_000,
    currentBid: 920_000,
    totalBids: 18,
    watchers: 271,
    startsAt: new Date(Date.now() - 21_600_000),
    endsAt:   new Date(Date.now() + 21_600_000),
    status: AuctionStatus.Active,
    isFeatured: false,
  },
  {
    id: '8',
    title: 'Leica M3 Double Stroke + Summicron 50mm f/2',
    description: 'Serial #700xxx, CLA 2023, pristine glass.',
    imageUrls: [],
    categoryId: 'cameras',
    sellerId: 'u8',
    startingPrice: 40_000,
    currentBid: 75_000,
    totalBids: 11,
    watchers: 56,
    startsAt: new Date(Date.now() - 14_400_000),
    endsAt:   new Date(Date.now() + 28_800_000),
    status: AuctionStatus.Active,
    isFeatured: false,
  },
]

export const MOCK_BIDS: BidHistoryItem[] = [
  { id: 'b1', auctionId: '1', bidderId: 'u5', amount: 135_000, placedAt: new Date(Date.now() - 60_000),  isAutoBid: false, bidderName: 'Alex K.',    isCurrentUser: false, isWinning: true  },
  { id: 'b2', auctionId: '1', bidderId: 'u6', amount: 130_000, placedAt: new Date(Date.now() - 180_000), isAutoBid: true,  bidderName: 'Maya S.',    isCurrentUser: false, isWinning: false },
  { id: 'b3', auctionId: '1', bidderId: 'me', amount: 125_000, placedAt: new Date(Date.now() - 300_000), isAutoBid: false, bidderName: 'You',        isCurrentUser: true,  isWinning: false },
]
